trigger:
  branches:
    include:
      - master  # Replace 'master' with the branch you want to trigger the pipeline on

pool:
  name: Default  # Replace 'YourSelfHostedAgentPool' with the name of your agent pool

steps:
- checkout: self  # This step checks out the code from the repository into the agent workspace

- script: |
    mkdir C:\Windows\System32\agent\temp1  # Replace 'C:\Windows\System32\agent\temp1'
    copy "$(Agent.BuildDirectory)\s\YourRepo\Source\Folder\*" C:\Windows\System32\agent\temp1
  displayName: 'Copy files to folder'
